dependencies:
  - python=3
  - pip:
    - numpy
    - matplotlib
    - pandas
    - beautifulsoup4
    - bs4
    - requests
    - scipy
    - scikit-learn
    - seaborn
    - pyecharts
    - statsmodels
    - fancyimpute
    - networkx
    - nxviz
    - pkuseg
    - efficient_apriori
