dependencies:
  - python = 3
  - pip:
    - numpy
    - matplotlib
    - pandas
    - requests
    - recognizers_text_suite
    - textblob
    - collections
    - opencv-python
    - Datetime
    - tourch
    - parsel
